apiVersion: v1
kind: Secret
metadata:
    name: homarr-secrets
stringData:
    SECRET_ENCRYPTION_KEY: ENC[AES256_GCM,data:/39GU4w3iWVS4CxbNJQY9yvj4YHKdI0sjiDCp9HYfE6RVNQ3L10UN2oJRGDTlh0WxQVQ9VFUwRGfBbXrDRHa1A==,iv:6Naq2GryG4o9Cxv7O6kwNp52Z3UtoYiUe0NpVrAEoiM=,tag:qUoNrezUhGyQ6IzJefiDHA==,type:str]
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNSTRxdDQxYTBNWVhPdHBl
            YzBodGFXWjVHVXRRTDdDS1pQa21pa1NQdlQ4Cnl0Ync1VWUrV0RiNCtsRXZxc2c3
            VHVKYmZkSHNCNm5SdjNsemdGd2s2dEUKLS0tIEZnaHdaU1hna1d0d1pURkpBaEtJ
            QlhYTzhybnBYOTROeU5UY3VaR3FwQ0UKe5YYTpOuFi9NP7fPXuZrhd41+QeSM19w
            fpBchwFr0wMR8bMMRcI5sJ+aAo8lmUNEfh2MJb9n2gnxbCx2iexyuA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T08:54:51Z"
    mac: ENC[AES256_GCM,data:ZRnqjJMqzphSfsa0jbOLm7Ha5jk0wXmkUFRzb7QCUg93U0fPR/S7P17lzF82QDt27QyLyRP7XoRDuZh+wfIkB+cg9wbD3G3bQSAVk5n4+OutvQ9xrZwzOQP7NG4kKHBZoNfwo3EdQBpHozFeid5V4hXedObfWS2VeyGDA5kivjQ=,iv:8+819sikiM+1wvAs9LMD6sArphZVeBJ1BciXIf7Rh0I=,tag:zdhEoioQ0dnbVeAHjdpgnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
