apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homelab-runners
  namespace: arc-runners
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set
      version: "0.10.1"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-systems
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    githubConfigUrl: "https://github.com/milanoid"
    githubConfigSecret: github-pat
    minRunners: 0
    maxRunners: 3
    containerMode:
      type: "dind"
    template:
      spec:
        containers:
          - name: runner
            resources:
              requests:
                cpu: "500m"
                memory: "1Gi"
              limits:
                cpu: "2"
                memory: "2Gi"
