---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webhosting
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webhosting
  template:
    metadata:
      labels:
        app: webhosting
    spec:
      containers:
        - name: nginx
          image: nginx:1.29.7@sha256:381b45aeb56e1ab20ed5ec5fe6483f44050d9ce1a837575f0d1333a6c6e4e251
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: webhosting-data
      volumes:
        - name: webhosting-data
          persistentVolumeClaim:
            claimName: webhosting-data-pvc
