apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:AUr3GSYYq953anaFv9b9qrg3KYS0pryrYhL7i2sUrNa9G3HPpbgeUYt/H2ep85eL7xVlYSLMyYLPDui1oAqn25XjZBR1erCtqSpxXire5rJxgWM7oIh/d20BHljhO0ENj+wDT2wC4G9yQvgyTv0l1jVGZKolTP+WgVVI9IltYtbGyQHj2YW0flDGGNGuzjdPNP6amLZ+KwPyl+geN2vX3En8QbgDdo0pX3LbtA8a5VVJMfLphzHK6RfHzlDJeIEGziIYZyZOCN1+T1rpQCAxnUCvkSQ+llDvzONvVauWoVPfKq99aJTurhK6BOI=,iv:l3ueKeKsxTyesKzz5IDNMWRkfJVU6oVj2uzLvLRCzXk=,tag:4mYB3aVwen2KiUMIokgp8A==,type:str]
kind: Secret
metadata:
    name: audiobooks-tunnel-credentials
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGamJIOXEwQlNSN3E2TjRk
            N3hHdEx2VHRzSjhtdm8yRElTYlJ0alR6TjNvCmpWbnc3dEpneS95cUJUNkJaVVZE
            eVBOVVBPdkdON2kycE1NSHQ5MmtxcXcKLS0tIHpBNGw1OXp0N2YyWlVadXFhVk50
            OWlDUUpFTndtRUliTDA0NVFTNUpFek0Ks8sQof/MKfqq8ff4d7pzZp3Cy0uO6uAE
            n3KCnvNaqpZIkny/yD/BrA4e+kMJ4Ahqb00RAubk201R45VViFlPLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-19T11:44:33Z"
    mac: ENC[AES256_GCM,data:xPHR30vTfzlP8O2vlC5mR4a6dmFlO1cWqeqGETyTZBnTvxI2EE0Ni4HFUZivfCJCDrPrUU6dlMYP7MoSX+NPqg24mI6qnhytoi5CtdmLTUsqr01bDinuBgkZj4/bSEbbbRrvUGPLEqtyfM8A5ZGHL589Tyh1Acap9Fys8CTKSSo=,iv:LgLwRQjJxPz50BO/lin4ZenLZAoJpsZjBrKQLJ4tLlg=,tag:zhy/abNeSjDS1KRRJbMYLg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
