apiVersion: v1
kind: Secret
metadata:
    name: github-pat
    namespace: arc-runners
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:Bd/fzvC3fvqj2nOVprj0lgzd9JITLY2f7SLHUosV1kqMA1Z3Qpw3LQ==,iv:gUns+OMA97xuEAj3w80SR0HmKreYQiRwN24/SthN7yk=,tag:9bSFq+FRsNCGht7vtf+iOA==,type:str]
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBENjJrZVhSQ0lnUW1sU01q
            cWNIYTBaa3hPcFRod3J2V3JmM0d0ZFRxeFVBCmNKMldWaXdZMWRicHcrakNzbjZn
            T1JJVkNNbHNnWEtLK2QrQkdRdDZDVWMKLS0tIExIbDNiUmREMXNyYS9WaTZBNnpv
            VDJ2dFV3U3ZVbkM3YzY5V2EzQllYODgKXJZmPF3NqKSp7BG2oXNGaaCCYkB4E1xU
            nJjTLY9Qv8aM/MSgSp6WHfj421xyzTk6vnq7XnMK7NDxy8mDSyOnIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T19:21:15Z"
    mac: ENC[AES256_GCM,data:4RDJ08sb6UQRN4+bwYQQquqkFLWc6p5behxm00F0RR9hn0+aA95K6dqP5rv/zsaoMMwOMuUol8USbk2sN9C/IXtOxccLdsO9hOZNAteqgRfEQ05ROdiSC/OpDEcWFBW5RdDdDzz0lOAyoFVrmNfHMAnGKY6GpElCPfcmMGWr7S8=,iv:6QHKRarayezl2mgO/2FyWyk9OKbSijBGcx497N8KO0o=,tag:NsFO1ScrQag0b43dpX6+rw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
