apiVersion: v1
kind: Secret
metadata:
    name: github-pat
    namespace: arc-runners
type: Opaque
stringData:
    github_token: ENC[AES256_GCM,data:eThvQPs8+QxSGhiVzWDQTou7KaUTcguwpAzlDtNn0GqlxzWlPBLJ/g==,iv:ykq0g7+pyXF6D8mCbjOXhennukkuW9PIkIEmHEyghOk=,tag:U5TE4cUxENjWHI41w2qVNQ==,type:str]
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeHZuWkpkQUNTSXpWcXFN
            WGR1RkY1eXA5R2Y5ZjJJcTdhRTIwM3Z1Mmh3Ck11OUppUXdRQ1YxcGpXZ1BqZmlj
            bGlMUHU1d1Mwbkh4TjJkZ21KVkJ6ODgKLS0tIE1mcG9JeWhiM0RjZ1RCTk1BSFR6
            VEh0b0xvK2JoSEwxMStvcjdBMDN1QUEKrYrPsuERymkw71iqO+oh0BrVoVuNVnoz
            SiuvG03+fQHmpOpggC+sW4ZsQ0jXIY3suy9Kkq3C7E/uZKnsifPPjQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T17:49:04Z"
    mac: ENC[AES256_GCM,data:zXGZpTB9f8L2WY8Azb9g3NzjZ25U0+gut5fTqVy8AA8IvUs8cFBWWyEJe+s3nGusDCaBAVm4NfGzy4rHZUY9uzHA8O0Gi7lMFDC91R7o023ba0EfWZeYK6yIymhN+oKMv1nMPPpJ4wFbns1noxxBm9qqGqGwevTdBtWtLhpopXg=,iv:vzr24G6kLGrnr66WntPFqQhtCAXv4+6IFesM8dOKwJU=,tag:rMKoK+cgd6HHokLGd2v9Gg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
