apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-password
    namespace: downloaders
type: Opaque
stringData:
    WEBUI_PASSWORD: ENC[AES256_GCM,data:5WE6nOV0qzFJ,iv:l/+VkMY3+fV2K2QYeDOfmnDbazLePAFAhqhl20hpieI=,tag:qFUvY/VaVbccWSN7n7wL3A==,type:str]
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvblJGYU5BTDk1aVVKS3lk
            UUVPb2NvVUJIQnBOMTh0ZW1IUm5pYlJQbFdRCnNPYWdRVE5HYk1VRmQwNlpmRy9o
            TTVlQTk5aU9FcytnY0FxRy85S1oyVG8KLS0tIFRyU0Jtd1hkbjJ3ZVd3MThScTMr
            Y1RIazIvZHdUbGhpOWhRZVpMS3RTbncKZg26fbApVcJistNrMk+0erhj4GoXJw8B
            5Ad1JSHKwzVwpTdlYjKLY37cQmdlH5VzgnnF6rSBRvNV5uUpqN0jPw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-02T20:44:43Z"
    mac: ENC[AES256_GCM,data:omwxXkeZirEI30TV3UZoI/0xk2L1G4XWnTK7gNHTA0slCeiXTgplmlMG3vOOMAXv7W1xYUtjlEvhw8POg4NH8+rm7U7Thz9w2hbrK9PhBcu6UQ7XR3iPiRrbgyEs9sOWLK06vbKf4VMU4spSAHzewpuGalAYtP8jWQDmn0OjhK8=,iv:he7b7f9TT87x80ErKDOXzImVzvIejqd0jbOFeZf9o40=,tag:xw6gzOerWTuwn0HSZ+db8g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
