---
apiVersion: v1
kind: ConfigMap
metadata:
  name: audiobookshelf-configmap
  namespace: audiobookshelf
data:
  PORT: "9005"
  TZ: "Europe/Prague"
  #CONFIG_PATH: "/audiobookshelf/config"
  #METADATA_PATH: "/audiobookshelf/metadata"
