---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: audiobookshelf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.30.0
          envFrom:
            - configMapRef:
                name: audiobookshelf-configmap
          ports:
            - containerPort: 3005
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: audiobookshelf-config
            - mountPath: /audiobooks
              name: audiobookshelf-audiobooks
            - mountPath: /metadata
              name: audiobookshelf-metadata
          securityContext:
            allowPrivilegesEscalation: false
            runAsUser: 1000  # user `node`
      restartPolicy: Always
      volumes:
        - name: audiobookshelf-config
          persistentVolumeClaim:
            claimName: config-pvc
        - name: audiobookshelf-audiobooks
          persistentVolumeClaim:
            claimName: audiobooks-pvc
        - name: audiobookshelf-metadata
          persistentVolumeClaim:
            claimName: metadata-pvc
