apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:qJ/anRSbSWW96T6yuqGEYMY8kmyFZaNJYH07rv2yEHav2WwIbx+w8rhqWmwD0YEJjjlU1JcYD/cXVgopJ8dnnx3TF7EYUlGp3vbodAUHtNc+CHKc+xLWXFIjh9OzSphpcJizxU1wqHOcpsMO3KqO7V+xzZ1RVeIQCNcpk06F1G0+2T+W8qi8AK15Il4gM2Fl2DkNo+N4wtVuX6I22g+wYaA3umF4Qq8HH6RzwehDutAEufAS8BMCTyVep/4b8D9YCNzI8KCzuOgQDwg1NsIBBCogyK7zcKBQSxNsWh2yUreXoVxiFlmTCBoCpVE=,iv:hk58nex+JWx8dzmir0lT8D64lcvruXugd6PsXimrKcw=,tag:QOvX8mG9CfZzJIVcrWytFg==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsd0dOdjNVL2pBRTJZM1ZG
            K2wydjU4TmZ5NWVoRTdTZUxWVC9nVitPM0hjClNVOUxTNENaNjVXRHRFZmJEZDlG
            Nmx1ZmVTOXFIVTBWMm9DWEJhUFFTVVUKLS0tIE1MTjN0WTQ5dUNmWWxRSXVNcnVZ
            WnpIYURHMmZ3bGdwZlpldnBDWDdCZjAKY8C+iPbhKOXBiOheb0q0IxrnODQwRqXW
            U+z7grumt3fXclDMXMxDI3hVp8W9H1MaFOQbax5jOJDwNKz94hMHjA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-08-17T18:43:38Z"
    mac: ENC[AES256_GCM,data:wWdztlf9pL0kLSmmn3SBR370zfm2NxQoI0LV84RRjwHsdxauFhA8S46ACs+r5M0L7F6/qcbra2ATZUGcBjIeX8H/qR77MK/2ZOP8pzfjZ0bPJ+xkhNh4IhXnOUQ6LQkSRUDrg6yo5VEcOCbiMRo4esdwSAkJzMu2cB9gvbXvwTI=,iv:HlCVpG3EOb9lJ4mkCArS/am3PolyqC2ZF25jDQ3fwIc=,tag:tjc5a9uVOmbSSNPZ/DuYhg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
