apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:X08zttiWha13dHnYsIaaMyoGaL8lbsiFS64mjnSWrzH3Xjz4GCvSRwl8RoMGnIQDXIWtFF1rrme7AEsSBMgUeAsx8eUNWqbUoj/Dr+bz+khIFL3CLqfrV0P44z7QL/tm57cVuqHi7H3NpDZ5va6IZkSIoxqiUcYM5Kj6S1DiU1Nd+C0JTsvkG+64Hg7YSndRQBpimd0acBai9P4mJ0NX3ltLN03uNzLW4VBytfnRJPXX02Qz9qgRqKEcgYl2ynyKX2HW9kL+SvWJo4SXs6rJcVlK/qjo3jxdrhWhxsy/D0TE92MQfq0aokVfkfs=,iv:sJItSm35TNdTWDrn6DNRRiIuzuC4RJ68T72b1G+gGjk=,tag:IC7Zlu5H7MA/brTTUmcX/Q==,type:str]
kind: Secret
metadata:
    name: argocd-badge-tunnel-credentials
    namespace: argocd
sops:
    age:
        - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWSjFZemlvemc0ekR3RDNL
            YjJlejNreU5HTDZkVzY2WmQ0amlBYjBIYm5nCmJaQlhtT1NieENjUXg2S2ZtNFVw
            UGs1VlNaNEJkRFZ2NXFJcVFIdWg2WkEKLS0tIGJwbkxGY2FINlpCblpWTFB5WmE3
            bUtRNUhER3VLVUNKSS82VkszT0p1c2cK/VN2S2dvMrnDdjzRZcGQfMej6LywNaPZ
            MpAq/TFbwAooQ5gd6LE28Nxtk1nDJtTZlWnvTIXMHwQiJTfnCJaeFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-17T07:26:39Z"
    mac: ENC[AES256_GCM,data:58J2o5PjveTOSq5ufmKD0YQn7LFWU1MjjllmXxpxx0CyJTuMHEXBpqtqukkPRqBzsDHXXjZ8zKp5vWeSxdFiLS11d02KkdjefcAMhNPzXVfOgp+ML2wm1mtU3qhDaLzeza2OZPVso2/+EmGl+hClBBMJ3Tr84adtVhUoGCvY9UQ=,iv:gvgUaGIBlyihKQdv3qSn8ILYI2yEIE7ODBE7Y7gHCjU=,tag:Jltiz9VmHT7Av8HhNRoPHA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
