apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "v2.35.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 12h
  values:
    admin:
      existingSecret: "pihole-password"
      passwordKey: "password"

    # Using existingClaim to preserve data from previous Helm CLI deployment
    # The PVC "pihole" already exists on the cluster (created 34 days ago)
    # This prevents data loss during migration from Helm CLI to Flux GitOps
    persistentVolumeClaim:
      enabled: true
      existingClaim: "pihole"
      size: 500Mi
      accessModes:
        - ReadWriteOnce

    serviceDns:
      mixedService: true
      type: LoadBalancer
      loadBalancerIP: "192.168.1.232"
      externalTrafficPolicy: Local

    serviceWeb:
      type: ClusterIP

    ingress:
      enabled: false

    doh:
      enabled: true
      envVars:
        TUNNEL_DNS_UPSTREAM: "https://1.1.1.2/dns-query"

    DNS1: 8.8.8.8
    DNS2: 8.8.4.4

    capabilities:
      add:
        - SYS_TIME
        - SYS_NICE

    podDnsConfig:
      enabled: true
      policy: "None"
      nameservers:
        - 127.0.0.1
        - 8.8.8.8

    extraEnvVars:
      TZ: Europe/Prague

    nodeSelector:
      kubernetes.io/hostname: hpmini02

