apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pihole
  namespace: pihole
spec:
  interval: 30m
  chart:
    spec:
      chart: pihole
      version: "v2.35.0"
      sourceRef:
        kind: HelmRepository
        name: mojo2600
        namespace: pihole
      interval: 12h
  values:
    adminPassword: admin # todo - into sacrets
    persistentVolumeClaim:
      enabled: true
      size: 500Mi
      accessModes:
         - ReadWriteOnce

    serviceDns:
      mixedService: true
      type: LoadBalancer
      externalTrafficPolicy: Local

    serviceWeb:
      type: ClusterIP

    ingress:
      enabled: false

    extraEnvVars:
      TZ: America/Chicago
      FTLCONF_dns_upstreams: "1.1.1.2" # Malware Blocking Only https://blog.cloudflare.com/introducing-1-1-1-1-for-families/

