apiVersion: v1
kind: PersistentVolume
metadata:
  name: synology-nfs-pv
spec:
  storageClassName: ""
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /volume1/k8s
    server: 192.168.1.36
  persistentVolumeReclaimPolicy: Retain
