apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:bHg/Ees=,iv:3tJgqA0A6CU7fhoN3t9/L/mzI+vDFWugA821H+EoojY=,tag:lTCgrBGbeqP849Qz83JW0w==,type:str]
    admin-password: ENC[AES256_GCM,data:WdqcCJRtY4fDHb+AsCliIevJ1a7L3zSQ,iv:/4aGVkcCAvxk3MRX13IfHIPqtiOJj7qtFjnz8xhnkd0=,tag:0uQfp+0lC8gPVzf9UPBvbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLSzVmeTF0OStwbG15RUZT
            K3dqN3J6UlRwRGh5allodngwUmhQeFZPS1drCnJtek9iaDkyUFdXWDdSK3lnTFk5
            Rmh0ZFFpQUw4ZUIzY2xRbGU0K05VRlUKLS0tIGtsZmZqSS9mOEtlM0thNVAvY29M
            UkVtVEUzWDFtZUpnL3V0SnRRaEFJVWMKK9JeUNl+noI6iD11abOjzuTEqN4iCq0W
            Y5O8/XZilllYrQXDYXXRtnjZEjrcCZYo/ER4Yc4rJfsJnVSNtpVxTw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T11:11:11Z"
    mac: ENC[AES256_GCM,data:K/gIgC0xoawzMx+NBSQ41eI9bWM0Ml2DbjuDL3/04XggvTL4mh+v5aiobWRi6/jDhDm2nUvgrVZJe7j6IVigNyfoUERNSppFX4Z2a2ZC6zx+TBaOK5IOS293b0RjfjhlyaB0thOkDlTMo5JMLfYCnQyY1ljv9+fVJ7LzzpJxGL8=,iv:tEVL+rkgUp/EK3ASHVAK7z0tIhyNLvnqUV55hvGKLFM=,tag:PGEUfPFSM5Z0l6793pzJzw==,type:str]
    version: 3.13.3
