apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-controller
  namespace: arc-systems
spec:
  interval: 30m
  chart:
    spec:
      chart: gha-runner-scale-set-controller
      version: "0.10.1"
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-systems
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  driftDetection:
    mode: enabled
  values:
    resources:
      limits:
        memory: 256Mi
        cpu: 500m
      requests:
        memory: 128Mi
        cpu: 100m
