apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: actions-runner-controller
  namespace: arc-systems
spec:
  type: oci
  interval: 24h
  url: oci://ghcr.io/actions/actions-runner-controller-charts
