apiVersion: v1
kind: ConfigMap
metadata:
  name: renovate-configmap
  namespace: renovate
data:
  RENOVATE_AUTODISCOVER: "false"
  RENOVATE_GIT_AUTHOR: "Renovate Bot <bot@renovateapp.com>"
  RENOVATE_PLATFORM: "github"
  GITHUB_APP_ID: "3219089"
  GITHUB_INSTALLATION_ID: "119949905"
  LOG_LEVEL: "debug"
