apiVersion: v1
data:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:plmc0U8K+9PlGc9NuomcnXnAJMzGvDSj0d5t/Xd51NZg/m2usQyz1PlWzKcTBTV6b8jbL7y4hR4=,iv:h5FWGhGXF3xuXFoH/xmR15HgDNEgAX4pgCsQFQ6B9qE=,tag:Xrp27BcAzZBQhIjzZR/Uwg==,type:str]
kind: Secret
metadata:
  creationTimestamp: null
  name: renovate-container-env
sops:
  age:
    - recipient: age1jnfhet7cj900tg9f0dwgqktjwux4km4hen8gnevpujm5260sayesujm92y
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2VXNsalRJb0dnQXVLRjZl
        ZmxMTU5UUTZuVm4zQk9KQ2wvTzBKSC9UZkFzCmZ2UUtIaXVOL3NoMW8rOFUrMnRE
        RmxmRmhISHRYVVNPYUZWMnZCcndmTXMKLS0tIE5tTFgvYkNCTmFDc3BwMnJsRTM1
        N3VObEwwL3pTYzgvdm5IVmkyR0xyNGsK7lOQ2L+VmoDnxR22JqC3XlUWnzlMdoa+
        2iaupG7fpN0VCObHq7ELcwDu+YlUERv3mlLPjgxwD5Wt19+Utma1Yw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-26T16:32:14Z"
  mac: ENC[AES256_GCM,data:nLNwogr4/0yedu6tpoNUAgah/wdYlC8Oc1i/B2xyPnE0jKhUnV2+qeSNrLVJBoGTS790MIOWKAB5un0g9btChMUTXiPHvYokNkz4QB+I8Tj4Rp4AutJoTR0EDubyy+IuMoehrhTg+wIjzlflWf6Q3H4lb+JM4w2saWljcJa0cBQ=,iv:gT33ve/dQxSoZPLS4pJrt5emCR8tX7erjeOhHyVaCpU=,tag:cXhChNyGojtBDQYfUD6gfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  version: 3.11.0
